name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-base-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev pkg-config

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: python-requirements-${{ env.pythonLocation }}-${{ github.event.pull_request.base.sha || github.sha }}
          restore-keys: |
            python-requirements-${{ env.pythonLocation }}
            python-requirements-

      - name: Install package
        run: |
          pip install --upgrade --upgrade-strategy eager -e '.'

      - name: Run Python linting
        run: |
          make static-checks

      - name: Run Python tests
        run: |
          make test

      - name: Check Rust lint
        run: |
          cargo fmt --check

      - name: Run Rust tests
        run: |
          cargo test

      - name: Save cache
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
